export const listRoadmaps = [
  {
    key: 1,
    icon: 'javascript',
    name: 'Javascript',
    modules: [
      {
        id: 1,
        content: '2234234',
        title: 'Basic Comcepts',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 2,
        content: '2234234',
        title: 'Syntax',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 3,
        content: '2234234',
        title: 'Functions',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
    ],
  },
  {
    key: 2,
    icon: 'angular',
    name: 'Angular.js',
    modules: [
      {
        id: 1,
        content: '2234234',
        title: 'Basic Comcepts',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 2,
        content: '2234234',
        title: 'Syntax',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 3,
        content: '2234234',
        title: 'Functions',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
    ],
  },
  {
    key: 3,
    icon: 'python',
    name: 'Python',
    modules: [
      {
        id: 1,
        content: '2234234',
        title: 'Basic Comcepts',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 2,
        content: '2234234',
        title: 'Syntax',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 3,
        content: '2234234',
        title: 'Functions',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
    ],
  },
  {
    key: 4,
    icon: 'vue',
    name: 'Vue.js',
    modules: [
      {
        id: 1,
        content: '2234234',
        title: 'Basic Comcepts',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 2,
        content: '2234234',
        title: 'Syntax',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 3,
        content: '2234234',
        title: 'Functions',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
    ],
  },
  {
    key: 5,
    icon: 'csharp',
    name: 'C# (C Sharp)',
    modules: [
      {
        id: 1,
        content: '2234234',
        title: 'Basic Comcepts',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 2,
        content: '2234234',
        title: 'Syntax',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
      {
        id: 3,
        content: '2234234',
        title: 'Functions',
        description: 'Learn the basic compects about javascript',
        links: [
          {
            key: 1,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 2,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
          {
            key: 3,
            language: 'br',
            level: 'easy',
            growMaster: '@MarcosReanto266',
            type: 'video',
            postDate: '22/02/1993',
            link: 'http://www.google.com',
            upvotes: 44,
            strikes: 0,
          },
        ],
      },
    ],
  },
];
